package Acme::CPANLists::Import::PerlAdvent::2003_12_21;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2003/21st/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Inline::Java"}],summary=>"Modules mentioned in Perl Advent Calendar 2003 (day 21)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2003 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2003/21st/> (retrieved on 2016-11-07). Visit the URL for the full contents.

