package Acme::CPANLists::Import::PerlAdvent::2003_12_08;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2003/8th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"CGI::Application"}],summary=>"Modules mentioned in Perl Advent Calendar 2003 (day 8)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2003 (day 8)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2003/8th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

