package Acme::CPANLists::Import::PerlAdvent::2003_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2003/20th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Regexp::Common"}],summary=>"Modules mentioned in Perl Advent Calendar 2003 (day 20)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2003 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2003/20th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

