package Acme::CPANLists::Import::PerlAdvent::2003_12_11;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2003/11th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"File::Basename"},{module=>"File::chdir"},{module=>"FindBin"}],summary=>"Modules mentioned in Perl Advent Calendar 2003 (day 11)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2003 (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2003/11th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

