package Acme::CPANLists::Import::PerlAdvent::2003;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2003/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"CGI::Untaint"},{module=>"HTML::Entities"},{module=>"Hook::LexWrap"},{module=>"PPerl"},{module=>"Template::Extract"},{module=>"Mail::SpamAssassin"},{module=>"Attribute::Handlers"},{module=>"CGI::Application"},{module=>"Data::Dimensions"},{module=>"Test::Inline"},{module=>"File::Basename"},{module=>"File::chdir"},{module=>"FindBin"},{module=>"Class::ISA"},{module=>"base"},{module=>"only"},{module=>"Date::Parse"},{module=>"Text::Glob"},{module=>"Math::BigInt"},{module=>"diagnostics"},{module=>"PDF::Reuse"},{module=>"Acme::Code::FreedomFighter"},{module=>"Regexp::Common"},{module=>"LWP::Simple"},{module=>"Data::Structure::Util"},{module=>"PAR"}],summary=>"Modules mentioned in Perl Advent Calendar 2003"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2003

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2003/> (retrieved on 2016-11-07). Visit the URL for the full contents.

